# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://0x30.io/
baseurl: /sustain/
title: Jonathan G.
author: Jonathan G.
description: Personal blog, projects & resume
avatar: profile.png
email: j@0x30.io
github: jekyller/sustain # ea1het
twitter: ea1het
linkedin: ea1het
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-00000000-0


# needed for travis-ci build
exclude: [vendor]
